name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Build with PyInstaller
        run: uv run pyinstaller jackfield_labeler.spec --noconfirm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jackfield-labeler-${{ matrix.os }}
          path: dist/jackfield_labeler*
